class MainMethodPerson{
public static void main(String[] args){
	System.out.println(" functionality of person");
	Person.sleep();
	Person.walk();
	Person.talk();
	Person.run();
	Person.dance();
	Person.sit();
	Person.eat();
	Person.drink();
	Person.exercise();
	Person.seeing();
	Person.listen();
	Person.read();
	Person.write();
	Person.work();
	Person.cooking();
	Person.tension();
	Person.searching();
	Person.yoga();
	Person.showering();
	Person.gardening();
	Person.caring();
		
					System.out.println(" \n");
						System.out.println(" functionality of WashingMachine");
						WashingMachine.washing();
						WashingMachine.rinsing();
						WashingMachine.spinning();
						WashingMachine.mainWash();
						WashingMachine.drycleaning();
						WashingMachine.sportsWearWash();
						WashingMachine.woolPlus();
						WashingMachine.darkWash();
						WashingMachine.heavyWash();
						WashingMachine.silentWash();
						WashingMachine.quickWash();
						WashingMachine.cottonClothWash();
						WashingMachine.synthetics();
						WashingMachine.babyCare();
						WashingMachine.dailyWash();
						WashingMachine.stainAway();
						WashingMachine.superEcoWash();
						WashingMachine.outdoorCare();
						WashingMachine.handWash();
						WashingMachine.temperatureChange();
						WashingMachine.delay();
						WashingMachine.end();
							System.out.println(" \n");
						System.out.println(" functionality of machanic");
						Mechanic.buildingMachines();
						Mechanic.assenblingMachines();
						Mechanic.inspectingMachines();
						Mechanic.inspectingEngines();
						Mechanic.inspectingTransmissios();
						Mechanic.troubleshooting();
						Mechanic.applyLubricats();
						Mechanic.replenishFluids();
						Mechanic.maintenance();
						Mechanic.preventiveMeasures();
						Mechanic.conductRegular();
						Mechanic.examineMachines();
						Mechanic.overseeDiagnosticTests();
						Mechanic.replaceBrokenParts();
						Mechanic.operatingMachines();
						Mechanic.monitorInventor();
						Mechanic.workWithCustomerToUnderstandTheirConcerns();
						Mechanic.diagnoseTheirproblem();
						Mechanic.explainVehicleRepairTOCustomer();
						Mechanic.explainMachineryRepairToCustomer();
						Mechanic.provideWorkEstimationForCustomers();
						Mechanic.updatedRecordsOfPreventiveMaintenance();
                           System.out.println(" \n");
						   System.out.println(" functionality of Barber");
						   Barber.hairCut();
						   Barber.trim();
						   Barber.shampoohair();
						   Barber.conditionApplyToHair();
						   Barber.styleHairUsingHotStylingTools();
						   Barber.coloringTheHair();
						   Barber.highlightHair();
						   Barber.groomFacialHair();
						   Barber.createUniqueStyles();
						   Barber.hairStyling();
						   Barber.hairDesign();
						   Barber.cosmeticProcedures();
						   Barber.manicures();
						   Barber.pedicures();
						   Barber.eyelashExtensions();
						   Barber.waxing();
						   Barber.makeupApplication();
						   Barber.botox();
						   Barber.lipFillers();
						   Barber.laserHairRemoval();
						   Barber.creativityToAdaptToAClientHair();
						   Barber.skinTreatments();
						   
						   
}
}

