package com.xworkz.encap.boot;

import com.xworkz.encap.app.Amazon;
import com.xworkz.encap.app.Cred;
import com.xworkz.encap.app.FaceBook;
import com.xworkz.encap.app.GitHub;
import com.xworkz.encap.app.Instagram;
import com.xworkz.encap.app.Irctc;
import com.xworkz.encap.app.LinkedIn;
import com.xworkz.encap.app.NammaMetro;
import com.xworkz.encap.app.NammaYatri;
import com.xworkz.encap.app.Netflix;
import com.xworkz.encap.app.Ola;
import com.xworkz.encap.app.PhonePe;
import com.xworkz.encap.app.Pubg;
import com.xworkz.encap.app.Rapido;
import com.xworkz.encap.app.RedBus;
import com.xworkz.encap.app.Snapchat;
import com.xworkz.encap.app.Uber;
import com.xworkz.encap.app.WhatsApp;
import com.xworkz.encap.app.YouTube;

public class MainRunner {

	public static void main(String[] args) {
		System.out.println("invoking main in mainRunner");
		System.out.println("\n");
		
        System.out.println("invoking NammaMetro");
		NammaMetro metro = new NammaMetro();
		metro.setOwner("BMRCL");
		metro.setLocale("Bengaluru");
		metro.setTransitType("Rapid transit");
		metro.setLineColor("Purple");
		metro.setNumberOfStation(63);
		metro.setdDailyRidership(703840l);
		metro.setAnnualRidership(174.22);
		metro.setChiefExecutive("Anjum Parvez");
		metro.setHeadQuaeters("BMTC complex Bengaluru");
		metro.setWebsite("bmtc.co.in");
		metro.setBeganOperation("20 October 2011");
		metro.setTrainLength(6);
		metro.setAverageSpeed(35);
		metro.setTopSpeed(80);
        System.out.println("owner is :" + metro.getOwner());
		System.out.println("locale is :" + metro.getLocale());
		System.out.println("transit type is :" + metro.getTransitType());
		System.out.println("line color  is :" + metro.getLineColor());
		System.out.println("Number Of Station  is :" + metro.getNumberOfStation());
		System.out.println("Daily Ridership  is :" + metro.getDailyRidership());
		System.out.println("Annual Ridership in million  is :" + metro.getAnnualRidership());
		System.out.println("ChiefExecutive  is :" + metro.getChiefExecutive());
		System.out.println("HeadQuaeters  is :" + metro.getHeadQuaeters());
		System.out.println("Website   is :" + metro.getWebsite());
		System.out.println(" Began Operation is :" + metro.getBeganOperation());
		System.out.println(" Train Length in coaches  is :" + metro.getTrainLength());
		System.out.println(" Average Speed is :" + metro.getAverageSpeed());
		System.out.println("Top Speed is :" + metro.getTopSpeed());
		System.out.println("\n");

        System.out.println("inboking Amazon");
		Amazon amazon = new Amazon();
		amazon.setTradeName("Amazon");
		amazon.setType("Public");
		amazon.setTradedAs("Nasdaq");
		amazon.setIsin("US0231351067");
		amazon.setFounded("july 5,1994");
		amazon.setFounder("Jeff Bezos");
		amazon.setAreaServed("Worldwide");
		amazon.setHeadquarters("Settle,Washington and Arlington,U.S");
		amazon.setKeyPeople("Jeff Bezos and Andy Jassy");
		amazon.setProducts("Echo.Fire tablet.fire Tv.Fire OS.kindle");
		amazon.setServices("Amazon.com,Amazon Alexa,Amazon Appstore,etc");
		amazon.setRevenue(13.98);
		amazon.setOperatingIncome(12.25);
		amazon.setTotalAssets(62.68);
		System.out.println("Trade Name is :" + amazon.getTradeName());
		System.out.println("Type is :" + amazon.getType());
		System.out.println("Trade As is :" + amazon.getTradedAs());
		System.out.println("ISIN is :" + amazon.getIsin());
		System.out.println("Founded in :" + amazon.getFounded());
		System.out.println("Founder Name is :" + amazon.getFounder());
		System.out.println("Area Served  is :" + amazon.getAreaServed());
		System.out.println("Headquarters  is :" + amazon.getHeadquarters());
		System.out.println("key people is :" + amazon.getKeyPeople());
		System.out.println("products is :" + amazon.getProducts());
		System.out.println("Services is :" + amazon.getServices());
		System.out.println("Revenue in billion is :" + amazon.getRevenue());
		System.out.println("operating income in billion is :" + amazon.getOperatingIncome());
		System.out.println("total assets in billion is :" + amazon.getTotalAssets());
		System.out.println("\n");

		System.out.println("invoking FaceBook");
		FaceBook faceBook = new FaceBook();
		faceBook.setType("Social networking");
		faceBook.setAvailableInLanguages(112);
		faceBook.setListOfLanguages("kannada,English,Hindi,Tamil,Telgu etc");
		faceBook.setFounded("Feb 4,2004");
		faceBook.setAreaServed("Worldwide,except blocking countries");
		faceBook.setOwner("Meta Platforms");
		faceBook.setFounders("Mark Zuckerberg,Dustin Moskovitz,Chris Hughes");
		faceBook.setCeo("Mark Zuckerberg");
		faceBook.setUrl("facebook.com");
		faceBook.setreRistration("Required");
		faceBook.setUsers(2.94);
		faceBook.setcurrentStatus("Active");
		faceBook.setWrittenIn("C++,Hack");
		faceBook.setWebsite("www.facebook.com");
		System.out.println("type of site is :" + faceBook.getType());
		System.out.println("Available In Languages is :" + faceBook.getAvailableInLanguages());
		System.out.println("List Of Languages is :" + faceBook.getListOfLanguages());
		System.out.println("Founded in :" + faceBook.getFounded());
		System.out.println("Area Served is :" + faceBook.getAreaServed());
		System.out.println("Owner is :" + faceBook.getOwner());
		System.out.println("Founders are :" + faceBook.getFounders());
		System.out.println("Ceo is :" + faceBook.getCeo());
		System.out.println("Urlis :" + faceBook.getUrl());
		System.out.println("Registration is :" + faceBook.getRegistration());
		System.out.println("Users  is :" + faceBook.getUsers());
		System.out.println("CurrentStatus is :" + faceBook.getCurrentStatus());
		System.out.println("WrittenIn :" + faceBook.getWrittenIn());
		System.out.println("Website is :" + faceBook.getWebsite());
		System.out.println("\n");

		System.out.println("invoking Netflix");
		Netflix netflix = new Netflix();
		netflix.setType("OTT platform");
		netflix.setAvailableInLanguages(99);
		netflix.setListOfLanguages("arabic,catalan,chinese,english,french etc");
		netflix.setHeadquarters("Los Gatos,California,U.S");
		netflix.setCountryOfOrigin("United States");
		netflix.setAreaServed("Worldwide,except china,north korea, russia and syria");
		netflix.setParent("Netflix,Inc");
		netflix.setUrl("www.netflix.com");
		netflix.setCommercial(true);
		netflix.setreRistration("Required");
		netflix.setUsers(238.39);
		netflix.setFounded("January 16,2007");
		netflix.setcurrentStatus("Active");
		netflix.setCeo("Reed Hastings");
		System.out.println("type is :" + netflix.getType());
		System.out.println("Available In Languages in :" + netflix.getAvailableInLanguages());
		System.out.println("List Of Languages are :" + netflix.getListOfLanguages());
		System.out.println("Headquarters in :" + netflix.getHeadquarters());
		System.out.println("Country Of Originis :" + netflix.getCountryOfOrigin());
		System.out.println("AreaServed :" + netflix.getAreaServed());
		System.out.println("Parent is :" + netflix.getParent());
		System.out.println("Url is :" + netflix.getUrl());
		System.out.println("Commercial :" + netflix.getCommercial());
		System.out.println("Registration is :" + netflix.getRegistration());
		System.out.println("Users is :" + netflix.getUsers());
		System.out.println("Founded in :" + netflix.getFounded());
		System.out.println("Ceo is :" + netflix.getCeo());
		System.out.println("\n");

		System.out.println("invoking IRCTC");
		Irctc irctc = new Irctc();
		irctc.setFullForm("Indian Railway Catering Tourism Corporation");
		irctc.setType("Public");
		irctc.setTradedAs("BSE:542830");
		irctc.setIsin("IN335Y01012");
		irctc.setFounded("27 september 1999");
		irctc.setHeadquarters("New Delhi,India");
		irctc.setAreaServed("India");
		irctc.setKeyPeople("Rajni Hasija,IRAS");
		irctc.setServices("online ticketing,Catering,Tourism,Hospital services");
		irctc.setRevenue(3541);
		irctc.setOperatingIncome(1354);
		irctc.setOwner("Government of India");
		irctc.setWebsite("www.irctc.co.in");
		irctc.setIndustry("Railways");
		System.out.println("Urctc full form is :" + irctc.getFullForm());
		System.out.println("type is :" + irctc.getType());
		System.out.println("Trade As is :" + irctc.getTradedAs());
		System.out.println("ISIN is :" + irctc.getIsin());
		System.out.println("Founded in :" + irctc.getFounded());
		System.out.println("Headquarters in :" + irctc.getHeadquarters());
		System.out.println("AreaServed :" + irctc.getAreaServed());
		System.out.println("key people is :" + irctc.getKeyPeople());
		System.out.println("Services is :" + irctc.getServices());
		System.out.println("Revenue in crors :" + irctc.getRevenue());
		System.out.println("operating income in crors :" + irctc.getOperatingIncome());
		System.out.println("Owner is :" + irctc.getOwner());
		System.out.println("Website is :" + irctc.getWebsite());
		System.out.println("industry is :" + irctc.getIndustry());
		System.out.println("\n");

		System.out.println("invoking LinkedIn");
		LinkedIn linkedIn = new LinkedIn();
		linkedIn.setType("Professional network");
		linkedIn.setAvailableIn("Multikingual");
		linkedIn.setFounded("May 5,2003");
		linkedIn.setHeadquarters("Sunnyvale,California,U.S");
		linkedIn.setAreaServed("Worldwide");
		linkedIn.setFounders("Reid Hoffman, Eric Ly");
		linkedIn.setCeo("Ryan Roslansky");
		linkedIn.setKeyPeople("Melissa Selcher,Raghu Hiremagaluru,James chuong");
		linkedIn.setIndustry("Internet");
		linkedIn.setRevenue(13.82);
		linkedIn.setParent("Microsoft");
		linkedIn.setUrl("www.linkedin.com");
		linkedIn.setreRistration("Required");
		linkedIn.setUsers(930);
		System.out.println("type is :" + linkedIn.getType());
		System.out.println("type is :" + linkedIn.getAvailableIn());
		System.out.println("Founded in :" + linkedIn.getFounded());
		System.out.println("Headquarters in :" + linkedIn.getHeadquarters());
		System.out.println("AreaServed :" + linkedIn.getAreaServed());
		System.out.println("Founders are :" + linkedIn.getFounders());
		System.out.println("Ceo is :" + linkedIn.getCeo());
		System.out.println("key people is :" + linkedIn.getKeyPeople());
		System.out.println("industry is :" + linkedIn.getIndustry());
		System.out.println("Revenue in crors :" + linkedIn.getRevenue());
		System.out.println("Parent is :" + linkedIn.getParent());
		System.out.println("Url is :" + linkedIn.getUrl());
		System.out.println("Registration is :" + linkedIn.getRegistration());
		System.out.println("Users is :" + linkedIn.getUsers());
		System.out.println("\n");

		System.out.println("invoking Cred");
		Cred cred = new Cred();
		cred.setType("private");
		cred.setIndustry("Financial service");
		cred.setFounded("2018");
		cred.setFounder("Kunal Shah");
		cred.setHeadquarters("Bangalore,India");
		cred.setRevenue(393);
		cred.setNetIncome(-1279);
		cred.setNumberOfEmployees(800);
		cred.setWebsite("cred.club");
		cred.setMarketingYear("2020-2023");
		cred.setProvides("short term credit lines");
		cred.setUsers(11.2);
		cred.setAreaServed("India");
		cred.setCeo("Kunal Shah");
		System.out.println("type is :" + cred.getType());
		System.out.println("industry is :" + cred.getIndustry());
		System.out.println("Founded in :" + cred.getFounded());
		System.out.println("Founder are :" + cred.getFounder());
		System.out.println("Headquarters in :" + cred.getHeadquarters());
		System.out.println("Revenue in crors :" + cred.getRevenue());
		System.out.println("NetIncome in crors :" + cred.getNetIncome());
		System.out.println("NumberOfEmployees :" + cred.getNumberOfEmployees());
		System.out.println("Website is :" + cred.getWebsite());
		System.out.println("MarketingYear is :" + cred.getMarketingYear());
		System.out.println("Provides is :" + cred.getProvides());
		System.out.println("Users is :" + cred.getUsers());
		System.out.println("AreaServed :" + cred.getAreaServed());
		System.out.println("Ceo is :" + cred.getCeo());
		System.out.println("\n");

		System.out.println("invoking Pubg");
		Pubg pubG = new Pubg();
		pubG.setcolor("Backgroung Cream");
		pubG.setOS("64 bit windows 10");
		pubG.setCPU("AMD Ryzen");
		pubG.setMemory(16);
		pubG.setDirect(11.0f);
		pubG.setStorage(512);
		pubG.setNetwork("Broadband internet");
		pubG.setPlayers(5);
		pubG.setMatchType("Deathmatch");
		pubG.setNetSpeed(564.8);
		pubG.setTime(5);
		pubG.setWeapen("Gun");
		pubG.setProtection("Shield");
		pubG.setNoOfLife(3);
		System.out.println(pubG.getColor());
		System.out.println(pubG.getColor());
		System.out.println(pubG.getCPU());
		System.out.println(pubG.getMemory());
		System.out.println(pubG.getDirect());
		System.out.println(pubG.getStorage());
		System.out.println(pubG.getNetwork());
		System.out.println(pubG.getPlayers());
		System.out.println(pubG.getMatchType());
		System.out.println(pubG.getNetSpeed());
		System.out.println(pubG.getTime());
		System.out.println(pubG.getWeapen());
		System.out.println(pubG.getProtection());
		System.out.println(pubG.getNoOfLife());
		System.out.println("\n");
		
		System.out.println("invoking RedBus");
		RedBus redBus = new RedBus();
		redBus.setTransport("in bus");
		System.out.println("transport in " + redBus.getTransport());
		redBus.setSize("Long");
		System.out.println("Size is " + redBus.getSize());
		redBus.setbodySize("Long");
		System.out.println("Body size " + redBus.getbodySize());
		redBus.setNoOfSeats(60);
		System.out.println("Total no of seats " + redBus.getNoOfSeats());
		redBus.setNoOfBenches(10);
		System.out.println("Total no of seats " + redBus.getNoOfBenches());
		redBus.setTarget("Bangalore");
		System.out.println("Target is " + redBus.getTarget());
		redBus.setTicketBooking("online mode");
		System.out.println("get ticket booking in " + redBus.getTicketBooking());
		redBus.setOnlineBooking("online booking for reservation");
		System.out.println("get ticket booking in " + redBus.getOnlineBooking());
		redBus.setNoOfPassengers(60);
		System.out.println("Total no of Passenger " + redBus.getNoOfPassengers());
		redBus.setBetterRoads("For smooth traveling");
		System.out.println("Get betterr raods for " + redBus.getBetterRoads());
		redBus.setDistance(150);
		System.out.println("Total distance " + redBus.getDistance());
		redBus.setTotalAmount(500);
		System.out.println("Total amount " + redBus.getTotalAmount());
		redBus.setGoogleMap("Hassan to bangalore");
		System.out.println("Roots " + redBus.getGoogleMap());
		System.out.println("\n");

        System.out.println("invoking Ola");
		Ola ola = new Ola();
		ola.setTransport("in bus");
		System.out.println("transport in " + ola.getTransport());
		ola.setSize("Long");
		System.out.println("Size is " + ola.getSize());
		ola.setAuto("Auto");
		System.out.println("Book  " + ola.getAuto());
		ola.setNoOfSeats(60);
		System.out.println("Total no of seats " + ola.getNoOfSeats());
		ola.setBike("Rapido");
		System.out.println("Total no of seats " + ola.getBike());
		ola.setTarget("Bangalore");
		System.out.println("Target is " + ola.getTarget());
		ola.setCar("Car");
		System.out.println("get booking in " + ola.getCar());
		ola.setOnlineBooking("online booking for reservation");
		System.out.println("get ticket booking in " + ola.getOnlineBooking());
		ola.setNoOfPassengers(60);
		System.out.println("Total no of Passenger " + ola.getNoOfPassengers());
		ola.setBetterRoads("For smooth traveling");
		System.out.println("Get betterr raods for " + ola.getBetterRoads());
		ola.setDistance(150);
		System.out.println("Total distance " + ola.getDistance());
		ola.setTotalAmount(500);
		System.out.println("Total amount " + ola.getTotalAmount());
		ola.setGoogleMap("Hassan to bangalore");
		System.out.println("Roots " + ola.getGoogleMap());
		System.out.println("\n");

		System.out.println("invoking Uber");
		Uber uber = new Uber();
		uber.setTransport("in bus");
		System.out.println("transport in " + uber.getTransport());
		uber.setSize("Long");
		System.out.println("Size is " + uber.getSize());
		uber.setAuto("Auto");
		System.out.println("Book  " + uber.getAuto());
		uber.setNoOfSeats(4);
		System.out.println("Total no of seats " + uber.getNoOfSeats());
		uber.setBike("Rapido");
		System.out.println("Total no of seats " + uber.getBike());
		uber.setTarget("Bangalore");
		System.out.println("Target is " + uber.getTarget());
		uber.setCar("Car");
		System.out.println("get booking in " + uber.getCar());
		uber.setOnlineBooking("online booking for reservation");
		System.out.println("get ticket booking in " + uber.getOnlineBooking());
		uber.setNoOfPassengers(4);
		System.out.println("Total no of Passenger " + uber.getNoOfPassengers());
		uber.setBetterRoads("For smooth traveling");
		System.out.println("Get betterr raods for " + uber.getBetterRoads());
		uber.setDistance(150);
		System.out.println("Total distance " + uber.getDistance());
		uber.setTotalAmount(600);
		System.out.println("Total amount " + uber.getTotalAmount());
		uber.setGoogleMap("Hassan to bangalore");
		System.out.println("Roots " + uber.getGoogleMap());
		System.out.println("\n");

		System.out.println("invoking Rapido");
		Rapido rapido=new Rapido();
		rapido.setTransport("in Bike");
		System.out.println("transport in "+rapido.getTransport());
		rapido.setSize("medium");
		System.out.println("Size is "+rapido.getSize());
		rapido.setElectric("Electric vehicle");
		System.out.println("Book  "+rapido.getlEectric());
		rapido.setNoOfSeats(4);
		System.out.println("Total no of seats "+rapido.getNoOfSeats());
		rapido.setBike("Rapido");
		System.out.println("Total no of seats "+rapido.getBike());
		rapido.setTarget("Bangalore");
		System.out.println("Target is "+rapido.getTarget());
		rapido.setScooty("Scooty");
		System.out.println("get booking in "+rapido.getScooty());
		rapido.setOnlineBooking("online booking for reservation");
		System.out.println("get ticket booking in "+rapido.getOnlineBooking());
		rapido.setNoOfPassengers(2);
		System.out.println("Total no of Passenger "+rapido.getNoOfPassengers());
		rapido.setBetterRoads("For smooth traveling");
		System.out.println("Get betterr raods for "+rapido.getBetterRoads());
		rapido.setDistance(10);
		System.out.println("Total distance "+rapido.getDistance());
		rapido.setTotalAmount(200);
		System.out.println("Total amount "+rapido.getTotalAmount());
		rapido.setGoogleMap("rajaji nagr to vijay nagar");
		System.out.println("Roots "+rapido.getGoogleMap());
		System.out.println("\n");
		
		System.out.println("invoking NammaYatri");
		NammaYatri nammaYathri=new NammaYatri();
		nammaYathri.setTransport("in bus");
		System.out.println("transport in "+nammaYathri.getTransport());
		nammaYathri.setSize("Long");
		System.out.println("Size is "+nammaYathri.getSize());
		nammaYathri.setAuto("Auto");
		System.out.println("Book  "+nammaYathri.getAuto());
		nammaYathri.setNoOfSeats(4);
		System.out.println("Total no of seats "+nammaYathri.getNoOfSeats());
		nammaYathri.setBike("Rapido");
		System.out.println("Total no of seats "+nammaYathri.getBike());
		nammaYathri.setTarget("Bangalore");
		System.out.println("Target is "+nammaYathri.getTarget());
		nammaYathri.setCar("Car");
		System.out.println("get booking in "+nammaYathri.getCar());
		nammaYathri.setOnlineBooking("online booking for reservation");
		System.out.println("get ticket booking in "+nammaYathri.getOnlineBooking());
		nammaYathri.setNoOfPassengers(4);
		System.out.println("Total no of Passenger "+nammaYathri.getNoOfPassengers());
		nammaYathri.setBetterRoads("For smooth traveling");
		System.out.println("Get betterr raods for "+nammaYathri.getBetterRoads());
		nammaYathri.setDistance(10);
		System.out.println("Total distance "+nammaYathri.getDistance());
		nammaYathri.setTotalAmount(600);
		System.out.println("Total amount "+nammaYathri.getTotalAmount());
		nammaYathri.setGoogleMap("mejestic to rajaji nagar");
		System.out.println("Roots "+nammaYathri.getGoogleMap());
		System.out.println("\n");
		
		System.out.println("invoking YouTube");
		YouTube youTube = new YouTube();
		youTube.setType(15);
		System.out.println("Type is:" + youTube.getType());
		youTube.setVesrion(1.6f);
		System.out.println("Vesion is:" + youTube.getVersion());
		youTube.setNoOfProperties(10);
		System.out.println("Properties is:" + youTube.getNoOfProperties());
		youTube.setFormat("Video Size");
		System.out.println("Format is:" + youTube.getFormat());
		youTube.setUpdates(true);
		System.out.println("Updates is:" + youTube.isUpdates());
		youTube.setPrivacy(true);
		System.out.println("privacy is:" + youTube.isPrivacy());
		youTube.setAdvantage("User Friendly");
		System.out.println("Advantages is:" + youTube.getAdvantage());
		youTube.setNoOfUsers(100);
		System.out.println("Number of Users is:" + youTube.getNoOfUsers());
		youTube.setSafe(false);
		System.out.println("YouTube is:" + youTube.isSafe());
		youTube.setChannelName("Music Hub");
		System.out.println("Channel Name is:" + youTube.getChannelName());
		youTube.setSubscribers(12);
		System.out.println("Subscribers is:" + youTube.getSubscribers());
		youTube.setUserName("Sushma");
		System.out.println("User Name is:" + youTube.getUserName());
		youTube.setPassword(true);
		System.out.println("Password is:" + youTube.isPassword());
		youTube.setInventor("Chad Hurley");
		System.out.println("Inventor Name is:" + youTube.getInventor());
		System.out.println("\n");
		
		System.out.println("invoking PhonePe");
		PhonePe phonePay = new PhonePe();
		phonePay.setFullForm("Unified Payments Interface");
		System.out.println("FullForm is:" + phonePay.getFullForm());
		phonePay.setVesrion(1.6f);
		System.out.println("Vesion is:" + phonePay.getVersion());
		phonePay.setamount(1000);
		System.out.println("Amount is:" + phonePay.getamount());
		phonePay.setFeatures("Recharge Mobile");
		System.out.println("Features is:" + phonePay.getFeatures());
		phonePay.setUpdates(true);
		System.out.println("Updates is:" + phonePay.isUpdates());
		phonePay.setPrivacy(true);
		System.out.println("privacy is:" + phonePay.isPrivacy());
		phonePay.setAdvantage("Easy Transaction");
		System.out.println("Advantages is:" + phonePay.getAdvantage());
		phonePay.setNoOfUsers(100);
		System.out.println("Number of Users is:" + phonePay.getNoOfUsers());
		phonePay.setSafe(true);
		System.out.println("Phone Pay is Safe:" + phonePay.isSafe());
		phonePay.setMyNumber(1234567891L);
		System.out.println("My Number is:" + phonePay.getMyNumber());
		phonePay.setInventorYear(2015);
		System.out.println("Invented Year is:" + phonePay.getInventorYear());
		phonePay.setUserName("Chandhu");
		System.out.println("User Name is:" + phonePay.getUserName());
		phonePay.setPassword(true);
		System.out.println("Password is:" + phonePay.isPassword());
		phonePay.setInventor("Sameer Nigam");
		System.out.println("Inventor Name is:" + phonePay.getInventor());
		System.out.println("\n");
		
		System.out.println("invoking gitHub");
		GitHub gitHub = new GitHub();
		gitHub.setType("Web Based");
		System.out.println("Type is:" + gitHub.getType());
		gitHub.setVesrion(1.8f);
		System.out.println("Version is" + gitHub.getVersion());
		gitHub.setNoOfContacts(10);
		System.out.println("NoOfContacts is:" + gitHub.getNoOfContacts());
		gitHub.setFeatures("CodeSpaces");
		System.out.println("Features is:" + gitHub.getFeatures());
		gitHub.setUpdates(true);
		System.out.println("Update is:" + gitHub.isUpdates());
		gitHub.setPrivacy(true);
		System.out.println("Privacy is:" + gitHub.isPrivacy());
		gitHub.setAdvantage("Easy to Share Codes");
		System.out.println("Advantages is:" + gitHub.getAdvantage());
		gitHub.setNoOfUsers(20);
		System.out.println("Number of Users is:" + gitHub.getNoOfUsers());
		gitHub.setRecordCalls(false);
		System.out.println("Record call is:" + gitHub.isRecordCalls());
		gitHub.setMyNumber(9880449303L);
		System.out.println("My Number is:" + gitHub.getMyNumber());
		gitHub.setInventorYear(2008);
		System.out.println("Inventor year is:" + gitHub.getInventorYear());
		gitHub.setUserName("Bindhu");
		System.out.println("User Name is:" + gitHub.getUserName());
		gitHub.setPassword(true);
		System.out.println("Password is:" + gitHub.isPassword());
		gitHub.setInventor("Scott Chacon");
		System.out.println("Inventor is:" + gitHub.getInventor());
		System.out.println("\n");
		
		System.out.println("invoking Snapchat");
		Snapchat snapchat = new Snapchat();
		snapchat.setType("Post Style");
		System.out.println("Type is:" + snapchat.getType());
		snapchat.setVesrion(1.6f);
		System.out.println("Vesion is:" + snapchat.getVersion());
		snapchat.setNoOfFollowers(100);
		System.out.println("Followers is:" + snapchat.getNoOfFollowers());
		snapchat.setFeatures("Photos");
		System.out.println("Features is:" + snapchat.getFeatures());
		snapchat.setUpdates(true);
		System.out.println("Updates is:" + snapchat.isUpdates());
		snapchat.setPrivacy(true);
		System.out.println("privacy is:" + snapchat.isPrivacy());
		snapchat.setAdvantage("One-On-One Communication");
		System.out.println("Advantages is:" + snapchat.getAdvantage());
		snapchat.setNoOfUsers(100);
		System.out.println("Number of Users is:" + snapchat.getNoOfUsers());
		snapchat.setRecordCalls(false);
		System.out.println("Record the call is:" + snapchat.isRecordCalls());
		snapchat.setMyNumber(1234567891L);
		System.out.println("My Number is:" + snapchat.getMyNumber());
		snapchat.setInventorYear(2011);
		System.out.println("Invented Year is:" + snapchat.getInventorYear());
		snapchat.setUserName("Sushma");
		System.out.println("User Name is:" + snapchat.getUserName());
		snapchat.setPassword(true);
		System.out.println("Password is:" + snapchat.isPassword());
		snapchat.setInventor("Evan Spiegel");
		System.out.println("Inventor Name is:" + snapchat.getInventor());
		System.out.println("\n");
		
		System.out.println("invoking Instagram");
		Instagram instagram = new Instagram();
		instagram.setType("Instagram lite");
		System.out.println("Type is:" + instagram.getType());
		instagram.setVesrion(1.6f);
		System.out.println("Vesion is:" + instagram.getVersion());
		instagram.setNoOfFollowers(100);
		System.out.println("Followers is:" + instagram.getNoOfFollowers());
		instagram.setFeatures("Posts");
		System.out.println("Features is:" + instagram.getFeatures());
		instagram.setUpdates(true);
		System.out.println("Updates is:" + instagram.isUpdates());
		instagram.setPrivacy(true);
		System.out.println("privacy is:" + instagram.isPrivacy());
		instagram.setAdvantage("Business Branding");
		System.out.println("Advantages is:" + instagram.getAdvantage());
		instagram.setNoOfUsers(100);
		System.out.println("Number of Users is:" + instagram.getNoOfUsers());
		instagram.setRecordCalls(false);
		System.out.println("Record the call is:" + instagram.isRecordCalls());
		instagram.setMyNumber(1234567891L);
		System.out.println("My Number is:" + instagram.getMyNumber());
		instagram.setInventorYear(2012);
		System.out.println("Invented Year is:" + instagram.getInventorYear());
		instagram.setUserName("Sachin");
		System.out.println("User Name is:" + instagram.getUserName());
		instagram.setPassword(true);
		System.out.println("Password is:" + instagram.isPassword());
		instagram.setInventor("Kevin Systrom");
		System.out.println("Inventor Name is:" + instagram.getInventor());
		System.out.println("\n");
		
		System.out.println("invoking whatsApp");
		WhatsApp whatsApp = new WhatsApp();
		whatsApp.setType("GB WhatsApp");
		System.out.println("Type is:" + whatsApp.getType());
		whatsApp.setVesrion(1.8f);
		System.out.println("Version is" + whatsApp.getVersion());
		whatsApp.setNoOfContacts(10);
		System.out.println("NoOfContacts is:" + whatsApp.getNoOfContacts());
		whatsApp.setFeatures("Italic");
		System.out.println("Features is:" + whatsApp.getFeatures());
		whatsApp.setUpdates(true);
		System.out.println("Update is:" + whatsApp.isUpdates());
		whatsApp.setPrivacy(true);
		System.out.println("Privacy is:" + whatsApp.isPrivacy());
		whatsApp.setAdvantage("Sharing Information");
		System.out.println("Advantages is:" + whatsApp.getAdvantage());
		whatsApp.setNoOfUsers(20);
		System.out.println("Number of Users is:" + whatsApp.getNoOfUsers());
		whatsApp.setRecordCalls(false);
		System.out.println("Record call is:" + whatsApp.isRecordCalls());
		whatsApp.setMyNumber(9880449303L);
		System.out.println("My Number is:" + whatsApp.getMyNumber());
		whatsApp.setInventorYear(1975);
		System.out.println("Inventor year is:" + whatsApp.getInventorYear());
		whatsApp.setUserName("Sachin");
		System.out.println("User Name is:" + whatsApp.getUserName());
		whatsApp.setPassword(true);
		System.out.println("Password is:" + whatsApp.isPassword());
		whatsApp.setInventor("Jan Koum");
		System.out.println("Inventor is:" + whatsApp.getInventor());
	}

}
